name: Build Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller requests
      
      - name: Build EXE
        run: pyinstaller --onefile --windowed calculadora.py

      - name: Install GitHub CLI
        run: choco install gh -y

      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh auth setup-git

      - name: Upload Release Asset using GH CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release upload "$GITHUB_REF_NAME" ./dist/calculadora.exe#calculadora.exe --clobber
